name: Check Requirements on Linux (.sh)

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  check-requirements:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: '3.9.9'

    - name: Install Docker
      uses: docker/setup-buildx-action@v3

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Make script executable
      run: |
        chmod +x tools/check_requirements/check_requirements.sh
        chmod +x tools/check_requirements/_core.sh

    - name: Run requirements check
      run: |
        cd tools/check_requirements
        ./check_requirements.sh
        if [ $? -ne 0 ]; then
          echo "Requirements check failed"
          exit 1
        fi 